# Use an official MySQL runtime as a parent image
FROM mysql:latest

# Set the root password for MySQL (change 'yourpassword' to your desired password)
ENV MYSQL_ROOT_PASSWORD 12345678

# Create a new database (change 'yourdbname' to your desired database name)
ENV MYSQL_DATABASE clinic

# Copy the initialization script to the Docker image
COPY ./init.sql /docker-entrypoint-initdb.d/
